version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gocritic
    - gosec
    - misspell
    - unparam
    - revive
  exclusions:
    rules:
      - path: examples/
        linters:
          - revive
        text: "package-comments"

formatters:
  enable:
    - gofmt

run:
  tests: false
  timeout: 1m

output:
  formats:
    text:
      path: stdout
      color: true
      print-linter-name: true
      print-issued-lines: true
