import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  changelog1: [{ type: "autogenerated", dirName: "v0.1.x" }],
  // changelog2: [{ type: "autogenerated", dirName: "v0.2.x" }],   // Uncomment this line to enable the second changelog version
};

export default sidebars;
